### ISSUE TITLE
The road to v1

### ISSUE THREAD

**Issue by davidwinter** [davidwinter/electron-forge-maker-snap#1]
This package aims to make packaging snap applications easy with `electron-forge`. Why, when there already seems to be "official" support within `electron-forge`? The current package doesn't appear to work with the latest `snap` version of `snapcraft`, and relies upon the `.deb` version instead which has been deprecated. Also, because PRs that have been opened attempting to improve and fix support are currently being left to go stale. Issues currently include:

- Browser sandboxing; it seems only "official" developers get sandboxing, so this should not be a default flag to include
- Environment variables for `snapcraft`; with multipass now being used, having the ability to tell `snapcraft` to build on the host machine rather than via `multipass` helps with things such as CI and debugging issues

I've started from using the simplest `snapcraft.yaml` file available to build simple Electron apps, and attempting to build an API around this that is compatible with `electron-forge` and its Makers system.

Before releasing a `v1`, I'd like to ensure that it supports a range of applications that are already packaging their applications with Snap.

I also would like for this package to have similar extension options to that of [`electron-builder`](https://www.electron.build/configuration/snap). I'm keen to hear from other application developers around their needs for extensibility.

Things to do:

- [x] Add [`debug`](https://www.npmjs.com/package/debug) support to assist with debugging
- [x] Try and resolve issue with VSCode and `snapcraft` [[1]](https://bugs.launchpad.net/snapcraft/+bug/1906660) [[2]](https://forum.snapcraft.io/t/snapcraft-blowing-up-with-a-python-error-without-tty-eg-snapcraft-version-version-txt/21399)
- [x] Include `snapcraft` output in `debug` logs
- [x] Match other `electron-builder` [customisation options](https://www.electron.build/configuration/snap) if needed
- [x] Investigate the template app that `electron-builder` uses that doesn't appear to require `snapcraft` at all
- [x] Ensure all values are included in either `snapcraft.yaml` or `.desktop` files
- [x] Remove underlying snap files on successful package creation and move into `make` directory top level

**Comment by davidwinter** [comment]
Hey, @rwwagner90 👋  I'd be really grateful if you could take a peek over this package, and let me know of any particular needs your application needs for `snap` packaging that I could ensure are catered for with this package.

For a very simple Electron app, it should work out of the box, and not have browser sandbox enabled by default.

**Comment by rwwagner90** [comment]
@davidwinter thanks for working on this! Would love to do everything with forge. Right now, I use electron-builder just for snap. This is my config:

```json
  "build": {
    "productName": "Swach",
    "linux": {
      "icon": "./resources/icon.png",
      "category": "Development",
      "description": "A robust color management tool for the modern age.",
      "synopsis": "A robust color management tool for the modern age.",
      "target": [
        "snap"
      ]
    },
    "snap": {
      "stagePackages": [
        "default",
        "giblib1",
        "libimlib2",
        "libx11-6",
        "libxcursor1",
        "libxfixes3",
        "scrot"
      ]
    }
  }
```

If everything from this config is supported, things should work for us!

**Comment by davidwinter** [comment]
@rwwagner90 it doesn't currently support `stagePackages` but give me a day or two... and we should be good to test! 👍

**Comment by davidwinter** [comment]
@rwwagner90 can you try giving `0.1.0` a spin?

```
makers: [
	...
	, {
		name: '@davidwinter/electron-forge-maker-snap',
		config: {
			stagePackages: [
				'default',
				'giblib1',
				'libimlib2',
				'libx11-6',
				'libxcursor1',
				'libxfixes3',
				'scrot'
			]
		}
	},
	...
]
```

**Comment by rwwagner90** [comment]
@davidwinter I forgot another thing we're doing is modifying the layout manually after the build:

```
          echo -e "layout:\n  /usr/lib/x86_64-linux-gnu/imlib2:\n    bind: \$SNAP/usr/lib/x86_64-linux-gnu/imlib2" >> ./dist/__snap-amd64/snap/snapcraft.yaml
          echo "Snapcraft.yaml modified contents w/ layout"
          cat ./dist/__snap-amd64/snap/snapcraft.yaml
          cd ./dist/__snap-amd64
          sudo snapcraft --destructive-mode
          sudo snapcraft push *.snap --release stable
```

Is it possible to pass any config for `layout` to this plugin?

**Comment by rwwagner90** [comment]
Also, how do I pass this?

```
    "productName": "Swach",
    "linux": {
      "icon": "./resources/icon.png",
      "category": "Development",
      "description": "A robust color management tool for the modern age.",
      "synopsis": "A robust color management tool for the modern age.",
```

**Comment by davidwinter** [comment]
@rwwagner90 I'll get `layout` supported shortly :+1: 

Regarding the other values:

- `icon` - do you have `packagerConfig` set within your forge config with an icon set? If so, it should pull from that automatically.
- `category` - see above https://github.com/davidwinter/electron-forge-maker-snap/issues/1#issuecomment-740098630
- `description` - if you have this set in `package.json` already, it will pull that in automatically
- `synopsis` - I'm using `summary` as per the snapcraft naming, and this will again automatically pull from `description` too if it is set

With any of the above, you can override these automatic values when specifying the `maker` config for this package with the `config` key, as above in the example.

I'll ping you when `layout` is sorted.

**Comment by davidwinter** [comment]
@rwwagner90 `0.2.0` should provide the `layout` stuff you need:

```
makers: [
	...
	, {
		name: '@davidwinter/electron-forge-maker-snap',
		config: {
			stagePackages: [
				'default',
				'giblib1',
				'libimlib2',
				'libx11-6',
				'libxcursor1',
				'libxfixes3',
				'scrot'
			],
			categories: ['Development'],
			layout: {
				'/usr/lib/x86_64-linux-gnu/imlib2': {
					bind: '$SNAP/usr/lib/x86_64-linux-gnu/imlib2'
				}
			}
		}
	},
	...
]
```

**Comment by rwwagner90** [comment]
Thanks @davidwinter! Will give it a try tomorrow.

**Comment by rwwagner90** [comment]
@davidwinter does this look correct?

```js
    {
      name: '@davidwinter/electron-forge-maker-snap',
      platforms: ['linux'],
      config: {
        categories: ['Development'],
        layout: {
          '/usr/lib/x86_64-linux-gnu/imlib2': {
            bind: '$SNAP/usr/lib/x86_64-linux-gnu/imlib2'
          }
        },
        stagePackages: [
          'default',
          'giblib1',
          'libimlib2',
          'libx11-6',
          'libxcursor1',
          'libxfixes3',
          'scrot'
        ]
      }
    }
```

I don't get any errors, but I also don't seem to get a `.snap` file generated. When my release runs, I get this:

`Error: Invalid value for '<snap-file>': File 'electron-app/out/**/*.snap' does not exist.`

**Comment by davidwinter** [comment]
@rwwagner90 can you paste the contents of `out/make/snapcraft/snap/snapcraft.yaml` please? I've got adding more debug information on my todo list, but the contents of that file should help.

**Comment by rwwagner90** [comment]
@davidwinter unfortunately, I build on GitHub actions, so I can't easily see the contents.

**Comment by rwwagner90** [comment]
@davidwinter I built locally on my Mac, and got it to build. There does not seem to be a generated `.snap` file anywhere. The contents of `snapcraft.yaml` appear okay:

```yml
name: swach
version: 0.4.10
icon: ./snap/gui/swach.png
summary: A robust color management tool for the modern age.
description: A robust color management tool for the modern age.
base: core18
confinement: strict
grade: stable
apps:
  swach:
    command: swach/swach --no-sandbox
    extensions:
      - gnome-3-34
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - unity7
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
parts:
  app:
    plugin: nil
    source: ./app
    override-build: cp -rv . $SNAPCRAFT_PART_INSTALL/swach
    stage-packages:
      - giblib1
      - libimlib2
      - libx11-6
      - libxcursor1
      - libxfixes3
      - scrot
      - libnss3
      - libnspr4
layout:
  /usr/lib/x86_64-linux-gnu/imlib2:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/imlib2
```

**Comment by rwwagner90** [comment]
Also, I think the icon path gets set wrong:

`Issues while validating snapcraft.yaml: Specified icon './snap/gui/swach.png' does not exist`

I think it should be ` './gui/swach.png'` since it's in the `snap` folder already maybe?

**Comment by rwwagner90** [comment]
TL;DR I either need an outputted `.snap` file or I need help with running `snapcraft --destructive-mode` to generate one.

**Comment by davidwinter** [comment]
@rwwagner90 thanks for all the debugging info - please leave it with me. I was having issues earlier with trying to get `snapcraft` to output a snap file outside of the directory that `snapcraft` runs, so I think it's something to do with that, and I'll just need to do a bit more digging to figure out what's going on.

Can you share the GitHub Actions command that is being run for the snap packaging, please?

Thanks for testing so far - really appreciate it!!!

**Comment by rwwagner90** [comment]
@davidwinter This is my current GH actions setup:

```yml
      - name: Install Snapcraft
        if: matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/')
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
      - name: Snapcraft release
        if: matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/')
        run: |
          cd electron-app/out/make/snapcraft
          sudo snapcraft --destructive-mode
          sudo snapcraft upload --release=stable *.snap
          cd ../../../../
```

I tried building the snap manually with `sudo snapcraft --destructive-mode` as you can see above, but I got:

```
Failed to generate snap metadata: The specified command 'swach/swach --no-sandbox' defined in the app 'swach' does not exist.
Ensure that 'swach/swach --no-sandbox' is installed with the correct path.
```

**Comment by davidwinter** [comment]
@rwwagner90 I've published v0.4.0 which adds a ton of debug output. Can you run on GitHub Actions with the following:

```
DEBUG='forge-maker-snap:*' electron-forge make --target="@davidwinter/electron-forge-maker-snap"
```

There will then be quite a lot of debug output when that has run, but if you could paste that in here, we can try and figure out what's happening.

With the icon error you received above, did you run the `snapcraft` command from within the `out/make/snapcraft` directory or `out/make/snapcraft/snap` directory? `snapcraft` seems to be really fussy, and expects it to be run from the former.

**Comment by rwwagner90** [comment]
@davidwinter I tried running locally and got this:

```
forge-maker-snap:snap-packager Snapcraft stdout: make -j2
  forge-maker-snap:snap-packager make install DESTDIR=/root/parts/gnome-3-34-extension/install
  forge-maker-snap:snap-packager Staging app 
  forge-maker-snap:snap-packager  +2s
  forge-maker-snap:snap-packager Snapcraft stdout: Staging gnome-3-34-extension 
  forge-maker-snap:snap-packager  +1s
  forge-maker-snap:snap-packager Snapcraft stdout: Priming app 
  forge-maker-snap:snap-packager  +1s
  forge-maker-snap:snap-packager Snapcraft stdout: Priming gnome-3-34-extension 
  forge-maker-snap:snap-packager  +4s
  forge-maker-snap:snap-packager Snapcraft stdout: Failed to generate snap metadata: The specified command 'swach/swach --no-sandbox' defined in the app 'swach' does not exist.
  forge-maker-snap:snap-packager Ensure that 'swach/swach --no-sandbox' is installed with the correct path.
  forge-maker-snap:snap-packager  +1s
  forge-maker-snap:snap-packager Snapcraft stdout: Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
  forge-maker-snap:snap-packager  +241ms
Stopping snapcraft-swach   +201ms                                               
  forge-maker-snap:snap-packager Snapcraft stdout:/ +1ms
  forge-maker-snap:snap-packager Snapcraft stdout:  +45ms
 +1ms                                                                           
  forge-maker-snap:snap-packager Snapcraft stdout: An error occurred when trying to execute 'sudo -H -i env SNAPCRAFT_BUILD_ENVIRONMENT=managed-host PATH=/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOME=/root SNAPCRAFT_HAS_TTY=False snapcraft snap --output swach-0.4.12.snap' with 'multipass': returned exit code 2.
  forge-maker-snap:snap-packager  +2ms
  forge-maker-snap:snap-packager Snapcraft has finished running, with a status code of: 2 +53ms
  forge-maker-snap:snap-packager Snapcraft encountered the following error (stderr): undefined +0ms
```

**Comment by rwwagner90** [comment]
Is `swach/swach` the correct command here or should it just be `swach`?

**Comment by rwwagner90** [comment]
@davidwinter actually, I think the issue might be Swach needs to be capitalized, so `swach/Swach`. I see in my normal `.deb` maker config I specify `bin: 'Swach',` and I see in the snapcraft output that there is a `app/Swach`.

**Comment by davidwinter** [comment]
Interesting. It should normally be, yes. Do you have a directory called `out/swach-linux-x64` in your project directory? If so, can you do an `ls - l` for me?

**Comment by davidwinter** [comment]
I guess potentially though that sanitization is mismatching with the binary that electron-forge is creating when it packages the app, so I might need to rework that assumption I'm making.

**Comment by rwwagner90** [comment]
@davidwinter yeah, I believe the executable is capitalized.

**Comment by rwwagner90** [comment]
Can we support a config like the `deb` maker does? Something like:

```
      config: {
        bin: 'Swach',
        name: 'swach',
        productName: 'Swach',
```

**Comment by davidwinter** [comment]
> Can we support a config like the `deb` maker does? Something like:
> 
> ```
>       config: {
>         bin: 'Swach',
>         name: 'swach',
>         productName: 'Swach',
> ```

I'm not sure we 100% would need to, seeing as electron-forge uses electron-packager under the hood to create the executable. If I just hook into whatever that is generating, then it should be completely seamless. I've just made the wrong assumption with this... and seeing as my app is all lowercase, never noticed it 😆 oops! Should have it sorted shortly 👍

**Comment by rwwagner90** [comment]
> > Can we support a config like the `deb` maker does? Something like:
> > ```
> >       config: {
> >         bin: 'Swach',
> >         name: 'swach',
> >         productName: 'Swach',
> > ```
> 
> I'm not sure we 100% would need to, seeing as electron-forge uses electron-packager under the hood to create the executable. If I just hook into whatever that is generating, then it should be completely seamless. I've just made the wrong assumption with this... and seeing as my app is all lowercase, never noticed it 😆 oops! Should have it sorted shortly 👍

Sounds great. Let me know when it's fixed!

**Comment by davidwinter** [comment]
It looks like if `productName` exists in your `package.json`, it'll use that, otherwise, it will fallback to `name` instead. 

Working on a fix.

**Comment by rwwagner90** [comment]
> It looks like if `productName` exists in your `package.json`, it'll use that, otherwise, it will fallback to `name` instead.
> 
> Working on a fix.

@davidwinter I have `productName` in my `deb` config, but not at the root. Please let me know what config to use to get the capitalized executable name, and hopefully that'll fix this up!

**Comment by davidwinter** [comment]
Cheers, and what is the value of `name` in `package.json` - is that `Swach` (capitalised)?

**Comment by rwwagner90** [comment]
@davidwinter no, it's lowercase, but the executable name is capitalized.

**Comment by rwwagner90** [comment]
```js
 packagerConfig: {
    asar: true,
    darwinDarkModeSupport: 'true',
    icon: 'electron-app/resources/icon',
    name: 'Swach',
```

I think this is where the capitalization comes from. We need it capitalized, so that the app shipped to users is capitalized.

**Comment by davidwinter** [comment]
Great, thanks 👍

**Comment by rwwagner90** [comment]
@davidwinter should we just remove the `toLowerCase` from here? https://github.com/davidwinter/electron-forge-maker-snap/blob/main/snap-values.js#L80

**Comment by davidwinter** [comment]
I don't think we can, because the `snapcraft.yaml` requires a lowercase `name` for the executable is creates: https://snapcraft.io/docs/snapcraft-yaml-reference

**Comment by davidwinter** [comment]
@rwwagner90 can you give `v0.4.1` a whirl please? :crossed_fingers: 

I'm using the filename generation that `electron-packager` uses under the hood to verify we use the correct executable, so _hopefully_ that fixes it.

**Comment by rwwagner90** [comment]
@davidwinter it now appears to be forcing a lowercase `swach` as the executable name, rather than allowing `swach/Swach`. I'm not sure this is an ideal solution. We want the app name to be capitalized, so it's not listed as lowercase `swach` in the store and lowercase in the users apps.

This is a minor concern we can resolve later though.

I'm going to try this on GitHub actions again and see if we get further.

**Comment by rwwagner90** [comment]
Is this expected to output a `.snap` now or should I still keep in the step to build one?

**Comment by davidwinter** [comment]
@rwwagner90 so within the `snapcraft.yaml` file it will appear as lowercase for the executable in the `command` section, but that's just for the snap internals, so safe to ignore that. If you want the capitalised name for the Snap store, add the following config for `applicationName`:

```
{
      name: '@davidwinter/electron-forge-maker-snap',
      platforms: ['linux'],
      config: {
        applicationName: 'Swach',
        categories: ['Development'],
        layout: {
          '/usr/lib/x86_64-linux-gnu/imlib2': {
            bind: '$SNAP/usr/lib/x86_64-linux-gnu/imlib2'
          }
        },
        stagePackages: [
          'default',
          'giblib1',
          'libimlib2',
          'libx11-6',
          'libxcursor1',
          'libxfixes3',
          'scrot'
        ]
      }
    }
```

The `applicationName` is used by the `title` key in the generated `snapcraft.yaml` that is used for the Snap Store title, and this will also be used for the Linux `.desktop` integration which is what appears in the 'Start' menu on Linux, or anywhere within Ubuntu, besides the command line, which will be the lower cased version.

**Comment by davidwinter** [comment]
> Is this expected to output a `.snap` now or should I still keep in the step to build one?

Yep, it should create it if you're using the `electron-forge make` command, and it should be output to `out/make/` once it has finished running.

**Comment by rwwagner90** [comment]
@davidwinter I got errors both locally and on GitHub actions. Local errors from trying to build on macOS:

```
Fetched 0 B in 0s (0 B/s)                                                       
  forge-maker-snap:snap-packager  +31s
  forge-maker-snap:snap-packager Snapcraft stdout: 
  forge-maker-snap:snap-packager  +0ms
  forge-maker-snap:snap-packager Snapcraft stdout: Traceback (most recent call last):
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/bin/snapcraft", line 33, in <module>
  forge-maker-snap:snap-packager     sys.exit(load_entry_point('snapcraft==4.4.4', 'console_scripts', 'snapcraft')())
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/click/core.py", line 829, in __call__
  forge-maker-snap:snap-packager     return self.main(*args, **kwargs)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/click/core.py", line 782, in main
  forge-maker-snap:snap-packager     rv = self.invoke(ctx)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
  forge-maker-snap:snap-packager     return _process_result(sub_ctx.command.invoke(sub_ctx))
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/cli/_command.py", line 89, in invoke
  forge-maker-snap:snap-packager     return super().invoke(ctx)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
  forge-maker-snap:snap-packager     return ctx.invoke(self.callback, **ctx.params)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/click/core.py", line 610, in invoke
  forge-maker-snap:snap-packager     return callback(*args, **kwargs)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/cli/lifecycle.py", line 382, in snap
  forge-maker-snap:snap-packager     _execute(steps.PRIME, parts=tuple(), pack_project=True, output=output, **kwargs)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/cli/lifecycle.py", line 92, in _execute
  forge-maker-snap:snap-packager     lifecycle.execute(step, project_config, parts)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 137, in execute
  forge-maker-snap:snap-packager     executor.run(step, part_names)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 191, in run
  forge-maker-snap:snap-packager     self._handle_step(part_names, part, step, current_step, cli_config)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 237, in _handle_step
  forge-maker-snap:snap-packager     self._handle_outdated(part, current_step, outdated_report, cli_config)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 376, in _handle_outdated
  forge-maker-snap:snap-packager     self._prepare_step(step=step, part=part)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 313, in _prepare_step
  forge-maker-snap:snap-packager     preparation_function()
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 467, in prepare_pull
  forge-maker-snap:snap-packager     self._unpack_stage_packages()
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 460, in _unpack_stage_packages
  forge-maker-snap:snap-packager     install_path=pathlib.Path(self.part_install_dir),
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/internal/repo/_deb.py", line 452, in unpack_stage_packages
  forge-maker-snap:snap-packager     cls.normalize(str(install_path))
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/internal/repo/_base.py", line 201, in normalize
  forge-maker-snap:snap-packager     cls._fix_shebangs(unpackdir)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/internal/repo/_base.py", line 290, in _fix_shebangs
  forge-maker-snap:snap-packager     mangling.rewrite_python_shebangs(unpackdir)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/internal/mangling.py", line 40, in rewrite_python_shebangs
  forge-maker-snap:snap-packager     root_dir, file_pattern, argless_shebang_pattern, r"#!/usr/bin/env \1"
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/file_utils.py", line 59, in replace_in_file
  forge-maker-snap:snap-packager     search_and_replace_contents(file_path, search_pattern, replacement)
  forge-maker-snap:snap-packager   File "/snap/snapcraft/5821/lib/python3.6/site-packages/snapcraft/file_utils.py", line 74, in search_and_replace_contents
  forge-maker-snap:snap-packager     original = f.read()
  forge-maker-snap:snap-packager MemoryError
  forge-maker-snap:snap-packager  +30ms
  forge-maker-snap:snap-packager Snapcraft stdout: Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
  forge-maker-snap:snap-packager  +201ms
Stopping snapcraft-swach   +195ms                                               
  forge-maker-snap:snap-packager Snapcraft stdout:/ +0ms
  forge-maker-snap:snap-packager Snapcraft stdout:  +26ms
 +2ms                                                                           
  forge-maker-snap:snap-packager Snapcraft stdout: An error occurred when trying to execute 'sudo -H -i env SNAPCRAFT_BUILD_ENVIRONMENT=managed-host HOME=/root SNAPCRAFT_HAS_TTY=False snapcraft snap --output swach-0.4.12.snap' with 'multipass': returned exit code 1.
  forge-maker-snap:snap-packager  +2ms
  forge-maker-snap:snap-packager Snapcraft has finished running, with a status code of: 2 +60ms
  forge-maker-snap:snap-packager Snapcraft encountered the following error (stderr): undefined +0ms
```

And the errors from GitHub actions: 

```
An error occured while making for target: snap

=================================================================================

ENV Summary:

  TIME: Wed Dec 09 2020 19:18:50 GMT+0000 (Coordinated Universal Time)
  TITLE: ember
  ARGV:
  - /opt/hostedtoolcache/node/12.20.0/x64/bin/node
  - /home/runner/work/swach/swach/node_modules/.bin/ember
  - electron:make
  EXEC_PATH: /opt/hostedtoolcache/node/12.20.0/x64/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /tmp/yarn--1607541370982-0.38107399740402625
  - /home/runner/work/swach/swach/node_modules/.bin
  - /home/runner/.config/yarn/link/node_modules/.bin
  - /home/runner/.yarn/bin
  - /opt/hostedtoolcache/node/12.20.0/x64/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /opt/hostedtoolcache/node/12.20.0/x64/lib/node_modules/npm/bin/node-gyp-bin
  - /opt/hostedtoolcache/node/12.20.0/x64/bin/node_modules/npm/bin/node-gyp-bin
  - /opt/hostedtoolcache/node/12.20.0/x64/bin
  - /home/linuxbrew/.linuxbrew/bin
  - /home/linuxbrew/.linuxbrew/sbin
  - /opt/pipx_bin
  - /usr/share/rust/.cargo/bin
  - /home/runner/.config/composer/vendor/bin
  - /home/runner/.dotnet/tools
  - /snap/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  PLATFORM: linux x64
  FREEMEM: 1245507584
  TOTALMEM: 7292203008
  UPTIME: 309
  LOADAVG: 1.94,1.31,0.6
  CPUS:
  - Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz - 2294
  - Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz - 2294
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.1
  - brotli: 1.0.9
  - cldr: 37.0
  - http_parser: 2.9.3
  - icu: 67.1
  - llhttp: 2.1.3
  - modules: 72
  - napi: 7
  - nghttp2: 1.41.0
  - node: 12.20.0
  - openssl: 1.1.1g
  - tz: 2019c
  - unicode: 13.0
  - uv: 1.40.0
  - v8: 7.8.279.23-node.45
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: An error occured while making for target: snap
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: An error occured while making for target: snap
  - name: [undefined]
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: 
Error: 
    at SnapPackager.createSnapPackage (/home/runner/work/swach/swach/electron-app/node_modules/@davidwinter/electron-forge-maker-snap/snap-packager.js:140:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

=================================================================================

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Does anything in there look like something you recognize? Not really sure what these errors are saying.

**Comment by davidwinter** [comment]
When it fails locally on your Mac, can you change directory into `out/make/snapcraft` and then run the `snapcraft` command to see if it is successful from there?

The only thing that seems to jump out at me is the `MemoryError`... are there any other debug lines above what you pasted in? I just wanted to check the debug information for the actual snapcraft command.

**Comment by davidwinter** [comment]
Just had a thought re GitHub Actions - can you paste the command you're using?

I _think_ for GitHub Actions, you'll need to prefix the command with this environment variable so that `snapcraft` doesn't use `multipass` on the CI machine, for example:

```
SNAPCRAFT_BUILD_ENVIRONMENT=host electron-forge make
```

May or may not be related...

**Comment by rwwagner90** [comment]
@davidwinter 

> When it fails locally on your Mac, can you change directory into out/make/snapcraft and then run the snapcraft command to see if it is successful from there?

I still get `An error occurred when trying to execute 'sudo -H -i env SNAPCRAFT_BUILD_ENVIRONMENT=managed-host HOME=/root SNAPCRAFT_HAS_TTY=True snapcraft snap' with 'multipass': returned exit code 1.`

> I think for GitHub Actions, you'll need to prefix the command with this environment variable so that snapcraft doesn't use multipass on the CI machine, for example:

I'm unfamiliar with this. Would I need it locally too? I don't know what multipass is.

**Comment by rwwagner90** [comment]
@davidwinter I'm also sometimes getting this locally `Snapcraft stdout: Failed to load plugin: unknown plugin: 'nil'`

**Comment by davidwinter** [comment]
We'll figure out GitHub Actions after, just so we don't get confused.

On your Mac, can you let me know what version of `snapcraft` and `multipass` you have?

```
snapcraft version
multipass version
```

`multipass` is the tool that `snapcraft` uses behind the scenes to spin up an Ubuntu virtual machine to actually do the packaging of your snap package on.

**Comment by rwwagner90** [comment]
`snapcraft, version 4.4.1`

```
multipass  1.5.0+mac
multipassd 1.5.0+mac
```

**Comment by davidwinter** [comment]
I have this issue sometimes on my Mac too, and I have to manually clean up the `multipass` virtual machines - which is a faff, but I've not found another workaround yet. Hopefully it will fix your problem.

Run `multipass list` to see a list of the virtual machines, then run `multipass delete <name>` to delete each one, and then run `multipass purge` after to actually remove them.

Then can you try again, please.

**Comment by davidwinter** [comment]
@rwwagner90 I've just managed to get this setup for my app that is now using GitHub Actions. All appears to have worked with the following setup within my job:

```yml
build_linux:
  needs: test

  runs-on: ubuntu-latest

  strategy:
    matrix:
      node-version: [14.x]

  steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Install project dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --no-progress --non-interactive

    - run: sudo snap install snapcraft --classic

    - run: yarn make
      env:
        DEBUG: "forge-maker-snap:*"
        SNAPCRAFT_BUILD_ENVIRONMENT: host

    - name: Upload snap artifact
      uses: actions/upload-artifact@v2
      with:
        path: out/make/*.snap
```

Can you try this with Actions and see how it plays out? And if it fails, can you share the debug output, please? :crossed_fingers:

**Comment by rwwagner90** [comment]
I still get `forge-maker-snap:snap-packager Snapcraft stdout: Failed to load plugin: unknown plugin: 'nil'` locally, even after deleting and purging multipass. I will try GitHub actions again.

**Comment by rwwagner90** [comment]
@davidwinter this is what I get from GitHub actions:

```
2020-12-09T23:35:10.414Z forge-maker-snap:snap-packager Snapcraft has been spawned within the directory: /home/runner/work/swach/swach/electron-app/out/make/snapcraft
2020-12-09T23:35:10.415Z forge-maker-snap:snap-packager Snapcraft has encountered an error and is aborting: Error: spawn snapcraft ENOENT
2020-12-09T23:35:10.415Z forge-maker-snap:snap-packager Snapcraft encountered the following error (stderr): undefined
An error occured while making for target: snap

=================================================================================

ENV Summary:

  TIME: Wed Dec 09 2020 23:35:10 GMT+0000 (Coordinated Universal Time)
  TITLE: ember
  ARGV:
  - /opt/hostedtoolcache/node/12.20.0/x64/bin/node
  - /home/runner/work/swach/swach/node_modules/.bin/ember
  - electron:make
  EXEC_PATH: /opt/hostedtoolcache/node/12.20.0/x64/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /tmp/yarn--1607556788857-0.5553884141817924
  - /home/runner/work/swach/swach/node_modules/.bin
  - /home/runner/.config/yarn/link/node_modules/.bin
  - /home/runner/.yarn/bin
  - /opt/hostedtoolcache/node/12.20.0/x64/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /opt/hostedtoolcache/node/12.20.0/x64/lib/node_modules/npm/bin/node-gyp-bin
  - /opt/hostedtoolcache/node/12.20.0/x64/bin/node_modules/npm/bin/node-gyp-bin
  - /opt/hostedtoolcache/node/12.20.0/x64/bin
  - /home/linuxbrew/.linuxbrew/bin
  - /home/linuxbrew/.linuxbrew/sbin
  - /opt/pipx_bin
  - /usr/share/rust/.cargo/bin
  - /home/runner/.config/composer/vendor/bin
  - /home/runner/.dotnet/tools
  - /snap/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  PLATFORM: linux x64
  FREEMEM: 1311043584
  TOTALMEM: 7292203008
  UPTIME: 243
  LOADAVG: 1.75,1.15,0.5
  CPUS:
  - Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz - 2593
  - Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz - 2593
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.1
  - brotli: 1.0.9
  - cldr: 37.0
  - http_parser: 2.9.3
  - icu: 67.1
  - llhttp: 2.1.3
  - modules: 72
  - napi: 7
  - nghttp2: 1.41.0
  - node: 12.20.0
  - openssl: 1.1.1g
  - tz: 2019c
  - unicode: 13.0
  - uv: 1.40.0
  - v8: 7.8.279.23-node.45
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: An error occured while making for target: snap
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: An error occured while making for target: snap
  - name: [undefined]
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: 
Error: 
    at SnapPackager.createSnapPackage (/home/runner/work/swach/swach/electron-app/node_modules/@davidwinter/electron-forge-maker-snap/snap-packager.js:142:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

=================================================================================

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rwwagner90** [comment]
I think maybe snap wasn't installed in time. Trying again. I did get a successful local build, so fingers crossed!

**Comment by rwwagner90** [comment]
@davidwinter it worked! The snap was built and published fine. Now I just need to get on Ubuntu and try it out.

**Comment by davidwinter** [comment]
:tada: 

Great stuff!! What snap channel has it been posted to? I use Ubuntu as well as a Mac so can give it a try if you like?

**Comment by davidwinter** [comment]
Installed and appears to run :+1:

**Comment by rwwagner90** [comment]
@davidwinter nice! The main thing to check is that the color eyedropper that uses `scrot` works. If you click the little droplet, it should take a screenshot with scrot and then let you pick colors from it. Do you mind giving it a try and poking around the app?

**Comment by davidwinter** [comment]
A few observations:

- The app launches fine initially, an icon appears in the menubar and the main window appears.
- If you click away from the app, and then the icon again, a menu appears, but it appears empty.
- Clicking the 'empty' menu item opens the window again.
- Using the eyedropper, a screenshot appears to be taken; I'm using a dual monitor setup, so the dual-screen screenshot is then only displayed on the primary monitor with the width reduced to one screen appearing squashed. This may just be a general problem and not necessarily related to the snap package itself?
- I _think_ when you use the eyedropper a sound is meant to happen? I notice an Alsa error in the console, and I think that is due to the default packages I'm using. In `electron-builder` there are a few other packages included by default, so I'll look into including those too if that is the case.

**Comment by rwwagner90** [comment]
@davidwinter 

> If you click away from the app, and then the icon again, a menu appears, but it appears empty.

This is an electron bug. A menu bar app in Linux doesn't handle clicks correctly and shows that empty menu until you click it. Basically all clicks are assumed to be right clicks trying to open a context menu, which is not correct. It's an unfortunate bug, and there doesn't seem to be any fix on the horizon.

> Using the eyedropper, a screenshot appears to be taken; I'm using a dual monitor setup, so the dual-screen screenshot is then only displayed on the primary monitor with the width reduced to one screen appearing squashed. This may just be a general problem and not necessarily related to the snap package itself?

Yeah, scrot should take a screenshot, then you should be able to use the dropper on it. When you use the dropper, I think there is a notification showing the color you chose, and it does play a sound by default, if all that is turned on in settings.

**Comment by davidwinter** [comment]
So the dropper works selecting a colour from it - it's just the screenshot of the dual monitor display is displayed only on one monitor, so it is squashed in width.

Besides the sound, which I'll get sorted, all seems to be working as expected?

**Comment by rwwagner90** [comment]
@davidwinter yeah, sounds like it works! I know dual monitor setups are finicky with scrot.

**Comment by davidwinter** [comment]
@rwwagner90 have released 0.6.0 with audio support. If you could repackage up, I can check that works as expected for you?

**Comment by rwwagner90** [comment]
@davidwinter sure thing, will give it a try now.

**Comment by davidwinter** [comment]
@rwwagner90 I'm going to close this issue now, as it looks like all seems good?

Thank you so much for helping me to test with another application. I really appreciate it. It's such a shame the official package seems to have gone dormant and stale. It makes me wonder if it was a mistake me migrating away from electron-builder to electron-forge in the first place...!

**Comment by rwwagner90** [comment]
@davidwinter thanks so much for working on this! Assuming the audio issue you mentioned is fixed, we should be good.

**Comment by davidwinter** [comment]
@rwwagner90 can you upgrade to 0.7.1 and republish the snap, please? Just noticed a bug that can cause the app the crash.

**Comment by rwwagner90** [comment]
@davidwinter sure thing, will do that now

**Comment by rwwagner90** [comment]
Releasing 0.4.17 now. Should be published shortly.

**Comment by davidwinter** [comment]
So I had a system beep when the screenshot happened, but still receive this error:

```
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM plug:default
```

But it all functionally seems to be working fine :+1:

**Comment by rwwagner90** [comment]
@davidwinter hmm, does `Audio` not work in Linux? This is what we have:

```js
      if (get(this, 'settings.sounds')) {
        const audio = new Audio('assets/sounds/pluck_short.wav');
        await audio.play();
      }

**Comment by davidwinter** [comment]
@rwwagner90 weird... so I thought I had by adding `libasound2` and `libpulse0` as part of the default stage packages, as that is what `electron-builder` was using.

**Comment by davidwinter** [comment]
@rwwagner90 what Audio API are you using? Within the renderer process or main?

**Comment by rwwagner90** [comment]
@davidwinter as far as I know, this one https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio

I suppose it is in the renderer, as it's on the Ember.js/client side.

**Comment by davidwinter** [comment]
Going to close this audio related issue. Please create a separate issue if it's still occurring for you - cheers!
